name: 🪲 Report a bug
description: Create a bug report to help improve ADVi3++ Firmware
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Do you want to ask a question? Are you looking for support? Please ask your questions on [ADVi3++ Community](https://community.advi3pp.com) (you have to be [a sponsor of the project](https://www.patreon.com/bePatron?u=6504486) to ask questions).

  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug in ADVi3++ Firmware.**

        ## Before Reporting a Bug

        - Read and understand our [Code of Conduct](https://github.com/andrivet/ADVi3pp/blob/master/.github/code_of_conduct.md). You are expected to comply with it, including treating everyone with respect.

        ## Instructions

        Please follow the instructions below. Failure to do so may result in your issue being closed. See [Contributing to ADVi3++](https://github.com/andrivet/ADVi3pp/blob/master/.github/contributing.md) for additional guidelines.

  - type: dropdown
    attributes:
      label: Did you check that your report is not a duplicate?
      description: >-
        Always check the other reports and be sure you are not reporting something already known.
      options:
        - Yes, I have checked and this is a new bug not previously reported.
        - No, I check it right now!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Bug Details

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Tell us what you were trying to do and what
        happened that you did not expect. Provide a clear and concise description of the
        problem and include as many details as possible.
      placeholder: |
        ADVi3++ does not make good coffee.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        What did you expect to happen?
      placeholder: I expected it to move left.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened instead?
      placeholder: It moved right instead of left.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >-
        Please describe the steps needed to reproduce the issue.
      placeholder: |
        1. [First Step] ...
        2. [Second Step] ...
        3. [and so on] ...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Your Setup

  - type: input
    attributes:
      label: Version of ADVi3++ Firmware
      description: "The version is written under the ADVi3++ logo on the LCD panel."
    validations:
      required: true

  - type: input
    attributes:
      label: Printer model
      description: Wanhao Duplicator i3 Plus or any clone (5.1), Aldi Balco 3D Printer UK (5.2C), Wanhao Duplicator i3 Plus Mark II (5.4). The exact version is written on the mainboard.
    validations:
      required: true

  - type: input
    attributes:
      label: Mods
      description: Please list any hardware mods that could be involved.

  - type: dropdown
    attributes:
      label: Bed Leveling
      description: What kind of bed leveling compensation are you using?
      options:
        - BLTouch (genuine)
        - BLTouch clone
        - Mark II proximity sensor
        - No Bed Leveling

  - type: dropdown
    attributes:
      label: Your Slicer
      description: Do you use Cura, Slic3r, Prusa Slicer, Simplify3D, IdeaMaker...?
      options:
        - Cura
        - Slic3r
        - Simplify3D
        - Prusa Slicer
        - IdeaMaker
        - Other (explain below)

  - type: dropdown
    attributes:
      label: Host Software
      description: Do you use OctoPrint, Repetier Host, Pronterface...?
      options:
        - SD Card (headless)
        - Repetier Host
        - OctoPrint
        - Pronterface
        - Cura
        - Same as my slicer
        - Other (explain below)

  - type: markdown
    attributes:
      value: >-
        ## Other things to include

        Please also be sure to include these items to help with troubleshooting:

          * **Log output** from the host such as OctoPrint or Pronterface
          * **Images** demonstrating the problem, if it helps to make it clear. **Please, NO VIDEO**.
          * **A G-Code file** that exposes the problem, if not affecting _all_ G-code.

        If you've made any other modifications to the firmware, please describe them in detail in the space provided.

        When pasting formatted text into the box below don't forget to put ` ``` ` (on its own line) before and after to make it readable.

  - type: textarea
    attributes:
      label: Additional information & file uploads
