blank_issues_enabled: false
contact_links:
  - name: 🛟 ADVi3++ Community Support
    url: https://community.advi3pp.com
    about: Please ask questions here (only for supporters of the project).
  - name: 📖 ADVi3++ Documentation
    url: https://manual.advi3pp.com
    about: Please report security vulnerabilities here.
  - name: 💸 Want to donate?
    url: https://www.patreon.com/bePatron?u=6504486
    about: Support ADVi3++ Firmware's development financially and get access to the full documentation and pre-built binaries!
