#
# ADVi3++ Firmware
# PlatformIO Configuration File
#

[advi3pp]
platform            = atmelavr
board               = megaatmega2560
build_flags         =
    ${common.build_flags}
    -std=gnu++1z
    -Wl,--relax
    -Werror
build_unflags       = -std=gnu++11
board_build.f_cpu   = 16000000L
src_filter          =
    ${common.default_src_filter}
    +<src/HAL/AVR>
upload_protocol     = custom
upload_port         = /dev/cu.usbmodem23101
upload_speed        = 115200
upload_kind         = usb
upload_flags =
    -v
    -D
    -V
    -C${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p$BOARD_MCU
    -P$UPLOAD_PORT
    -b$UPLOAD_SPEED
    -cwiring
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i

# For Windows, use something like:
#upload_port  = COM5
#upload_flags =
#  -D
#  -V
#  -C${platformio.packages_dir}/tool-avrdude/avrdude.conf
#  -p$BOARD_MCU
#  -P$UPLOAD_PORT
#  -b$UPLOAD_SPEED
#  -cwiring

[env:advi3pp_51]
extends             = advi3pp
build_flags         = ${advi3pp.build_flags} -DADVi3PP_51 -DNDEBUG

[env:advi3pp_51_bltouch]
extends             = advi3pp
build_flags         = ${advi3pp.build_flags} -DADVi3PP_51 -DBLTOUCH -DNDEBUG

[env:advi3pp_52c]
extends             = advi3pp
build_flags         = ${advi3pp.build_flags} -DADVi3PP_52C -DNDEBUG

[env:advi3pp_52c_bltouch]
extends             = advi3pp
build_flags         = ${advi3pp.build_flags} -DADVi3PP_52C -DBLTOUCH -DNDEBUG

[env:advi3pp_54]
extends             = advi3pp
build_flags         = ${advi3pp.build_flags} -DADVi3PP_54 -DNDEBUG

[env:advi3pp_54_bltouch]
extends             = advi3pp
build_flags         = ${advi3pp.build_flags} -DADVi3PP_54 -DBLTOUCH -DNDEBUG

[env:advi3pp_hw_simulator]
extends             = advi3pp
build_flags         = ${advi3pp.build_flags} -DADVi3PP_52C -DBLTOUCH -DADVi3PP_DEBUG -DADVi3PP_HARDWARE_SIMULATOR

#
# Native Simulation
#

[advi3pp_simulator]
platform          = native
framework         =
build_flags       =
    ${common.build_flags}
    -std=gnu++17
    -IMarlin
    -D__PLAT_NATIVE_SIM__
    -IMarlin/src/HAL/NATIVE_SIM
src_filter        =
    ${common.default_src_filter}
    +<src/HAL/NATIVE_SIM>
build_src_filter  =
    +<src/HAL/NATIVE_SIM>
lib_compat_mode   = off
lib_deps          =
    ${common.lib_deps}
    ADVi3++Simulator=file://../advi3pp-simulator/
extra_scripts     =
    ${common.extra_scripts}
    pre:buildroot/share/PlatformIO/scripts/simulator.py

[advi3pp_simulator_embedded]
platform          = native
framework         =
build_flags       =
    ${common.build_flags}
    -std=gnu++17
    -IMarlin
    -D__PLAT_NATIVE_SIM__
    -DDEBUG
    -IMarlin/src/HAL/NATIVE_SIM
    -IMarlin/src/advi3pp-simulator/src
    -IMarlin/src/advi3pp-simulator/include
    -IMarlin/src/advi3pp-simulator/vendor/imgui-1.90.6-docking
    -IMarlin/src/advi3pp-simulator/vendor/imgui-1.90.6-docking/backends
    -IMarlin/src/advi3pp-simulator/vendor/implot-f156599
    -IMarlin/src/advi3pp-simulator/vendor/ImGuiFileDialog-0.6.7
    -IMarlin/src/advi3pp-simulator/vendor/vcd-writer-b4fe347/include
    -IMarlin/src/advi3pp-simulator/vendor/glad/include
    -DIMGUI_IMPL_OPENGL_LOADER_GLAD
src_filter        =
    ${common.default_src_filter}
    +<src/HAL/NATIVE_SIM>
    +<src/advi3pp-simulator>
build_src_filter  =
    +<src/HAL/NATIVE_SIM>
    +<src/advi3pp-simulator/**/*.cpp>
    +<advi3pp-simulator/vendor/imgui-1.90.6-docking/*.cpp>
    +<advi3pp-simulator/vendor/imgui-1.90.6-docking/backends/*.cpp>
    +<advi3pp-simulator/vendor/implot-f156599/*.cpp>
    +<advi3pp-simulator/vendor/ImGuiFileDialog-0.6.7/*.cpp>
    +<advi3pp-simulator/vendor/vcd-writer-b4fe347/src/*.cpp>
    +<advi3pp-simulator/vendor/glad/glad.c>
lib_compat_mode   = off
lib_deps          =
    ${common.lib_deps}
extra_scripts     =
    ${common.extra_scripts}
    pre:buildroot/share/PlatformIO/scripts/simulator.py

#
# Simulator for macOS
#
# Use the script buildroot/bin/mac_gcc to prepare your environment.
#
# Homebrew:
#  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#
#  brew install gcc@14 glm mesa sdl2 sdl2_net
#
#  cd "$(brew --prefix)/bin"
#  rm -f gcc g++ cc
#  ln -s gcc-14 gcc ; sudo ln -s g++-14 g++ ; sudo ln -s g++ cc
#  cd -
#

[advi3pp_macos_arm64]
build_unflags     = -g2 -g3 -lGL -fstack-protector-strong
build_flags       =
    -mmacosx-version-min=10.13
    -DMACOSX_DEPLOYMENT_TARGET=10.13
    -DHAS_LIBBSD
    -I/opt/homebrew/include/
    -I/opt/homebrew/include/c++/14/
    -I/opt/homebrew/include/c++/14/aarch-apple-darwin24/
    -I/opt/homebrew/include/SDL2/
    -L/opt/homebrew/lib/
    -Wl,-framework,OpenGL
    -Wl,-framework,CoreFoundation
    -fno-stack-protector

[simulator_macos_x64]
build_unflags     = -g2 -g3 -lGL -fstack-protector-strong
build_flags       =
    -mmacosx-version-min=10.13
    -DMACOSX_DEPLOYMENT_TARGET=10.13
    -DHAS_LIBBSD
    -I/usr/local/include/
    -I/usr/local/include/c++/14/
    -I/usr/local/include/c++/14/x86_64-apple-darwin24/
    -I/usr/local/include/SDL2/
    -L/usr/local/lib/
    -Wl,-framework,OpenGL
    -Wl,-framework,CoreFoundation
    -fno-stack-protector

[env:advi3pp_macos]
extends         = advi3pp_simulator
build_type      = debug
build_flags     =
    ${advi3pp_simulator.build_flags}
    ${advi3pp_macos_arm64.build_flags}
    -Og
    -g3
    -gdwarf-4
    -D_THREAD_SAFE
    -DADVi3PP_DEBUG
debug_tool = lldb

[env:advi3pp_macos_embedded]
extends         = advi3pp_simulator_embedded
build_type      = debug
build_flags     =
    ${advi3pp_simulator_embedded.build_flags}
    ${advi3pp_macos_arm64.build_flags}
    -Og
    -g3
    -gdwarf-4
    -D_THREAD_SAFE
    -DADVi3PP_DEBUG
debug_tool = lldb
